name: Build

on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: levi106/drainsafe-manager

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Container registery
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Build and push to GitHub Container Registry
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: latest
        file: ./Dockerfile
        push: ${{ github.event_name != 'pull_request' }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
